name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Create Release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_16.0.app
      
      - name: Run tests
        run: swift test
      
      - name: Build documentation
        run: |
          swift package --allow-writing-to-directory ./docs \
            generate-documentation --target XCBuildKit \
            --disable-indexing \
            --transform-for-static-hosting \
            --hosting-base-path XCBuildKit \
            --output-path ./docs
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            ./docs/**/*
