name: Test & Documentation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app
      - name: Run tests
        run: swift test

  documentation:
    name: Documentation
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app
      - name: Build documentation
        run: |
          swift package --allow-writing-to-directory ./docs \
            generate-documentation --target XCBuildKit \
            --disable-indexing \
            --transform-for-static-hosting \
            --hosting-base-path XCBuildKit \
            --output-path ./docs
      - name: Upload documentation
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs

  deploy-docs:
    needs: documentation
    if: github.ref == 'refs/heads/main'
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
